storefront:
  password: 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
  theme_id: "124394373273"
  store: developfy101.myshopify.com

develop:
  password: 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
  theme_id: "124397256857"
  store: developfy101.myshopify.com

