storefront:
  password: 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
  theme_id: "124355772583"
  store: storefront-twentyone.myshopify.com

develop:
  password: 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
  theme_id: "124334014631"
  store: storefront-twentyone.myshopify.com

